name: Build and deploy Jekyll site to GitHub Pages

on: [push, pull_request]

env:
  JEKYLL_ENV: production

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
        id: rbenv

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rbenv.outputs.RUBY_VERSION }}"

      - run: |
          gem install bundler
          bundle install --path vendor/bundle

      - run: bundle exec jekyll build

      - name: Deploy blog
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'bnorm/blog.bnorm.dev' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: _site
          CLEAN: true
